[advisories]
ignore = [
  "RUSTSEC-2022-0093",  # dependency of Solana-sdk with a fixed version

  # Warnings
  "RUSTSEC-2021-0139",  #  ansi_term, solana dependency
  "RUSTSEC-2021-0145",  #  Atty, solana dependency
  "RUSTSEC-2023-0033",  #  Borsh, solana dependency
  "RUSTSEC-2023-0042",  #  Ouroboros, dependency of solana-runtime
]

