[advisories]
ignore = [
  "RUSTSEC-2022-0093",  # dependency of Solana-sdk with a fixed version
  "RUSTSEC-2024-0370",  # un-maintained proc-macro-error crate, nothing I can do about it
  "RUSTSEC-2024-0344",  # Solana dependency

  # Warnings
  "RUSTSEC-2021-0145",  #  Atty, solana dependency
  "RUSTSEC-2024-0375",  # un-maintained atty crate, nothing I can do about it
  "RUSTSEC-2024-0388",  # un-maintained derivative crate, nothing I can do about it
]

